# Generated by Django 4.2.9 on 2024-02-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_Sos', '0002_alter_collaborateur_date_d_entrée_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborateur',
            name='Date_d_entrée',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collaborateur',
            name='Date_de_Sortie',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collaborateur',
            name='N_CIN',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='collaborateur',
            name='N_Passeport',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='collaborateur',
            name='Nombre_d_enfants',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collaborateur',
            name='Prime',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collaborateur',
            name='Situation_familiale',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
