# Generated by Django 4.2.9 on 2024-02-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_Sos', '0004_collaborateur_taux_horaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborateur',
            name='Prime_Avancee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collaborateur',
            name='Taux_Horaire',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
