# Generated by Django 4.2.9 on 2024-02-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_Sos', '0005_collaborateur_prime_avancee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborateur',
            name='Rémunération',
        ),
        migrations.AddField(
            model_name='collaborateur',
            name='Slaire_base',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collaborateur',
            name='Age',
            field=models.PositiveBigIntegerField(),
        ),
    ]
