# Generated by Django 4.2.9 on 2024-02-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_Sos', '0007_alter_collaborateur_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborateur',
            name='Age',
            field=models.PositiveIntegerField(),
        ),
    ]
