# Generated by Django 4.2.9 on 2024-02-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_Sos', '0009_alter_collaborateur_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborateur',
            name='Slaire_base',
        ),
        migrations.AddField(
            model_name='collaborateur',
            name='Rémunération',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collaborateur',
            name='Age',
            field=models.PositiveIntegerField(),
        ),
    ]
