# Generated by Django 4.2.9 on 2024-02-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_Sos', '0011_remove_collaborateur_rémunération_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborateur',
            name='elapsed_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collaborateur',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collaborateur',
            name='stop_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
