# Generated by Django 4.2.9 on 2024-02-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_Sos', '0012_collaborateur_elapsed_time_collaborateur_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborateur',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='collaborateur',
            name='Nom',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='collaborateur',
            name='Prenom',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='collaborateur',
            name='Sexe',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='collaborateur',
            name='Statut',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
