# Generated by Django 4.2.9 on 2024-02-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_Sos', '0013_collaborateur_password_alter_collaborateur_nom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborateur',
            name='Log',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='collaborateur',
            name='Age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collaborateur',
            name='Date_de_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collaborateur',
            name='E_mail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
