# Generated by Django 4.2.9 on 2024-02-07 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_Sos', '0016_alter_collaborateur_salaire_base'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collaborateur',
            old_name='Log',
            new_name='username',
        ),
    ]
