# Generated by Django 4.2.9 on 2024-02-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_Sos', '0018_remove_collaborateur_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborateur',
            name='user',
        ),
        migrations.AddField(
            model_name='collaborateur',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='collaborateur',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
