# Generated by Django 4.2.9 on 2024-02-09 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_Sos', '0020_remove_collaborateur_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborateur',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
