# Generated by Django 4.2.9 on 2024-02-12 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_Sos', '0021_alter_collaborateur_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collaborateur',
            old_name='start_time',
            new_name='Work_Time',
        ),
        migrations.RemoveField(
            model_name='collaborateur',
            name='elapsed_time',
        ),
        migrations.RemoveField(
            model_name='collaborateur',
            name='stop_time',
        ),
    ]
