# Generated by Django 4.2.9 on 2024-02-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_Sos', '0022_rename_start_time_collaborateur_work_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborateur',
            name='Pause_Time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collaborateur',
            name='salaire_finale',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
