# Generated by Django 4.2.9 on 2024-02-12 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_Sos', '0023_collaborateur_pause_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collaborateur',
            old_name='Prime_Avancee',
            new_name='Salaire_Avancee',
        ),
    ]
