# Generated by Django 4.2.9 on 2024-02-13 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_Sos', '0024_rename_prime_avancee_collaborateur_salaire_avancee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborateur',
            name='Pause_Time',
        ),
        migrations.RemoveField(
            model_name='collaborateur',
            name='Work_Time',
        ),
    ]
