# Generated by Django 4.2.9 on 2024-02-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_Sos', '0025_remove_collaborateur_pause_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborateur',
            name='anciennetee',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
