# Generated by Django 4.2.9 on 2024-02-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_Sos', '0028_collaborateur_motif_de_départ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborateur',
            name='Commentaire',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='collaborateur',
            name='Motif_de_départ',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
