# Generated by Django 4.2.9 on 2024-02-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_Sos', '0029_alter_collaborateur_commentaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborateur',
            name='S_H',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
