# Generated by Django 4.2.9 on 2024-02-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_Sos', '0030_collaborateur_s_h'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborateur',
            name='Motif_de_départ',
            field=models.CharField(blank=True, choices=[('Demission', 'Demission'), ('Licenciement', 'Licenciement'), ('FPE', 'FPE'), ('Fin de contrat', 'Fin de contrat'), ('Comportement', 'Comportement'), ('Etudes', 'Etudes'), ('Sans motif(Volantaire)', 'Sans motif(Volantaire)')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='collaborateur',
            name='Statut',
            field=models.CharField(blank=True, choices=[('ACTIF', 'ACTIF'), ('INACTIF', 'INACTIF'), ('FORMATION', 'FORMATION'), ('STAGE', 'STAGE')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='collaborateur',
            name='Type_de_contrat',
            field=models.CharField(blank=True, choices=[('Etrange', 'Etrange'), ('Stage', 'Stage'), ('CDD', 'CDD'), ('CDI', 'CDI')], max_length=10, null=True),
        ),
    ]
