# Generated by Django 4.2.9 on 2024-02-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_Sos', '0034_alter_collaborateur_poste_alter_collaborateur_prime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborateur',
            name='Salaire_Avancee',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='collaborateur',
            name='Taux_Horaire',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
