# Generated by Django 4.2.9 on 2024-02-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_Sos', '0036_alter_collaborateur_nom_alter_collaborateur_prenom'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborateur',
            name='Declaration_CNSS',
            field=models.CharField(blank=True, choices=[('OUI', 'OUI'), ('NON', 'NON')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='collaborateur',
            name='Nombre_de_Jour_Travaille_Admin',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='collaborateur',
            name='Type_de_contrat',
            field=models.CharField(blank=True, choices=[('Etranger', 'Etrange'), ('Stage', 'Stage'), ('CDD', 'CDD'), ('CDI', 'CDI')], max_length=10, null=True),
        ),
    ]
