# Generated by Django 4.2.9 on 2024-02-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_Sos', '0037_collaborateur_declaration_cnss_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborateur',
            name='N_Passeport',
            field=models.CharField(blank=True, default='-', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='collaborateur',
            name='Type_de_contrat',
            field=models.CharField(blank=True, choices=[('Etranger', 'Etranger'), ('Stage', 'Stage'), ('CDD', 'CDD'), ('CDI', 'CDI')], max_length=10, null=True),
        ),
    ]
