# Generated by Django 4.2.9 on 2024-02-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_Sos', '0039_alter_collaborateur_adresse_postale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborateur',
            name='E_mail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
