# Generated by Django 4.2.9 on 2024-02-20 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_Sos', '0040_alter_collaborateur_e_mail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prime', models.FloatField(blank=True, default=0, null=True)),
                ('Taux_Horaire', models.FloatField(blank=True, default=0, null=True)),
                ('Salaire_Avancee', models.FloatField(blank=True, default=0, null=True)),
                ('salaire_finale', models.IntegerField(blank=True, default=0, null=True)),
                ('S_H', models.FloatField(blank=True, default=0, null=True)),
                ('id_Collaborateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_Sos.collaborateur')),
            ],
        ),
    ]
