# Generated by Django 4.2.9 on 2024-02-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_Sos', '0041_salaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborateur',
            name='Prime',
        ),
        migrations.RemoveField(
            model_name='collaborateur',
            name='S_H',
        ),
        migrations.RemoveField(
            model_name='collaborateur',
            name='Salaire_Avancee',
        ),
        migrations.RemoveField(
            model_name='collaborateur',
            name='Taux_Horaire',
        ),
        migrations.RemoveField(
            model_name='collaborateur',
            name='salaire_finale',
        ),
        migrations.AddField(
            model_name='salaire',
            name='Date_de_salaire',
            field=models.DateField(blank=True, null=True),
        ),
    ]
