# Generated by Django 4.2.9 on 2024-02-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_Sos', '0042_remove_collaborateur_prime_remove_collaborateur_s_h_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salaire',
            name='Prime',
        ),
        migrations.RemoveField(
            model_name='salaire',
            name='S_H',
        ),
        migrations.RemoveField(
            model_name='salaire',
            name='Salaire_Avancee',
        ),
        migrations.RemoveField(
            model_name='salaire',
            name='Taux_Horaire',
        ),
        migrations.AddField(
            model_name='collaborateur',
            name='Prime',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='collaborateur',
            name='S_H',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='collaborateur',
            name='Salaire_Avancee',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='collaborateur',
            name='Taux_Horaire',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
