# Generated by Django 4.2.9 on 2024-02-20 13:52

import admin_Sos.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_Sos', '0043_remove_salaire_prime_remove_salaire_s_h_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaire',
            name='Date_de_salaire',
            field=admin_Sos.models.MonthYearField(blank=True, max_length=7, null=True),
        ),
    ]
