# Generated by Django 4.2.9 on 2024-02-20 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_Sos', '0044_alter_salaire_date_de_salaire'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collaborateur',
            old_name='Prime',
            new_name='Avance_sur_salaire',
        ),
        migrations.RenameField(
            model_name='collaborateur',
            old_name='Salaire_Avancee',
            new_name='Prime_Produit',
        ),
    ]
