# Generated by Django 4.2.9 on 2024-02-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_Sos', '0045_rename_prime_collaborateur_avance_sur_salaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborateur',
            name='S_J_Admin',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
