# Generated by Django 4.2.9 on 2024-02-20 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_Sos', '0046_collaborateur_s_j_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborateur',
            name='S_J_Admin',
        ),
    ]
