# Generated by Django 4.2.9 on 2024-02-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_Sos', '0049_collaborateur_activite'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborateur',
            name='Planifer',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
