# Generated by Django 4.2.9 on 2024-02-23 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_Sos', '0051_rename_planifer_collaborateur_planifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborateur',
            name='Poste',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
