# Generated by Django 4.2.9 on 2024-02-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_Sos', '0052_alter_collaborateur_poste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborateur',
            name='Situation_familiale',
            field=models.CharField(blank=True, choices=[('Célibataire ', 'Célibataire'), ('Marié(e)', 'Marié(e)'), ('Divorcé(e)', 'Divorcé(e)'), ('Veuf(ve)', 'Veuf(ve)')], max_length=100, null=True),
        ),
    ]
