# Generated by Django 4.2.9 on 2024-02-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_Sos', '0053_alter_collaborateur_situation_familiale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborateur',
            name='Motif_de_départ',
            field=models.CharField(blank=True, choices=[('Demission', 'Demission'), ('Licenciement', 'Licenciement'), ('FPE', 'FPE'), ('Fin de contrat', 'Fin de contrat'), ('Comportement', 'Comportement'), ('Etudes', 'Etudes'), ('Sans motif(Volantaire)', 'Sans motif(Volantaire)'), ('Autre', 'Autre')], default='-', max_length=1000, null=True),
        ),
    ]
