# Generated by Django 4.2.9 on 2024-02-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_Sos', '0054_alter_collaborateur_motif_de_départ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborateur',
            name='Ville',
            field=models.CharField(blank=True, default='-', max_length=100, null=True),
        ),
    ]
