# Generated by Django 4.2.9 on 2024-02-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_Sos', '0055_alter_collaborateur_ville'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborateur',
            name='CSP',
            field=models.CharField(blank=True, choices=[('AGENT', 'AGENT'), ('CADRE', 'CADRE'), ('TECHNICIEN', 'TECHNICIEN'), ('STAGIAIRE', 'STAGIAIRE')], max_length=10, null=True),
        ),
    ]
