# Generated by Django 4.2.9 on 2024-02-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_Sos', '0056_collaborateur_csp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborateur',
            name='N_CIN',
            field=models.CharField(blank=True, default='-', max_length=120, null=True),
        ),
    ]
