# Generated by Django 4.2.9 on 2024-02-29 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_Sos', '0060_rename_salaire_salaire_canada_salaire_france'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collaborateur',
            old_name='Taux_Horaire',
            new_name='Nbre_d_heures_Travaillees',
        ),
    ]
