# Generated by Django 4.2.9 on 2024-03-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_Sos', '0061_rename_taux_horaire_collaborateur_nbre_d_heures_travaillees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaire_admin',
            name='salaire_finale',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='salaire_canada',
            name='salaire_finale',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='salaire_france',
            name='salaire_finale',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
