# Generated by Django 4.2.9 on 2024-03-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_Sos', '0062_alter_salaire_admin_salaire_finale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaire_admin',
            name='Avance_sur_salaire',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='salaire_admin',
            name='Nbre_d_heures_Travaillees',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='salaire_admin',
            name='Planifier',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='salaire_admin',
            name='Prime_Produit',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='salaire_admin',
            name='S_H',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='salaire_canada',
            name='Avance_sur_salaire',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='salaire_canada',
            name='Nbre_d_heures_Travaillees',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='salaire_canada',
            name='Planifier',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='salaire_canada',
            name='Prime_Produit',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='salaire_canada',
            name='S_H',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='salaire_france',
            name='Avance_sur_salaire',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='salaire_france',
            name='Nbre_d_heures_Travaillees',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='salaire_france',
            name='Planifier',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='salaire_france',
            name='Prime_Produit',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='salaire_france',
            name='S_H',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
