# Generated by Django 4.2.9 on 2024-03-05 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_Sos', '0063_salaire_admin_avance_sur_salaire_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salaire_admin',
            old_name='Nbre_d_heures_Travaillees',
            new_name='Nombre_de_Jour_Travaille_Admin',
        ),
        migrations.RemoveField(
            model_name='salaire_admin',
            name='Planifier',
        ),
        migrations.RemoveField(
            model_name='salaire_admin',
            name='Prime_Produit',
        ),
        migrations.RemoveField(
            model_name='salaire_admin',
            name='S_H',
        ),
    ]
