# Generated by Django 4.2.9 on 2024-03-11 14:24

import admin_Sos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_Sos', '0064_rename_nbre_d_heures_travaillees_salaire_admin_nombre_de_jour_travaille_admin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collaborateur_Turnover', models.FloatField(blank=True, default=0, null=True)),
                ('masse_salarial', models.BigIntegerField(blank=True, null=True)),
                ('date_rh', admin_Sos.models.MonthYearField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
