# Generated by Django 4.2.9 on 2024-04-02 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_Sos', '0066_evenet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Evenet',
            new_name='Event',
        ),
    ]
