# Generated by Django 4.2.9 on 2024-04-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_Sos', '0067_rename_evenet_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='priorite',
            field=models.CharField(blank=True, choices=[('ELEVE', 'ELEVE'), ('MOYENE', 'MOYENE'), ('FAIBLE', 'FAIBLE')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='Description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
