# Generated by Django 4.2.9 on 2024-04-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_Sos', '0068_event_priorite_alter_event_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Date_debut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='Date_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
