# Generated by Django 4.2.9 on 2024-04-17 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_Sos', '0069_event_date_debut_event_date_fin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Collaborateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_Sos.collaborateur')),
            ],
        ),
    ]
